# Generated by Django 3.1.5 on 2021-01-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ImageField(null=True, upload_to=None)),
                ('submitted_answer', models.TextField(blank=True)),
                ('correct_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('submitted_answer', models.CharField(blank=True, choices=[('1', 'option1'), ('2', 'option2'), ('3', 'option3'), ('4', 'option4')], max_length=100)),
                ('correct_answer', models.CharField(choices=[('1', 'option1'), ('2', 'option2'), ('3', 'option3'), ('4', 'option4')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShortAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('submitted_answer', models.TextField(blank=True)),
                ('correct_answer', models.TextField()),
            ],
        ),
    ]
